version: '2'
services:
    routeservice-app:
        image: routeservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://routeservice-postgresql:5432/RouteService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    routeservice-postgresql:
        extends:
            file: postgresql.yml
            service: routeservice-postgresql
