version: '2'
services:
    routeservice-app:
        image: firewolf2007/transport-logistic-routeservice
        environment:
            - SPRING_PROFILES_ACTIVE=dev,liquibase,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://routeservice-postgresql:5432/RouteService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timingservice-app:
        image: firewolf2007/transport-logistic-timingservice
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://routeservice-postgresql:5432/RouteService
            - JHIPSTER_SLEEP=30 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    routeservice-postgresql:
        extends:
            file: postgresql.yml
            service: routeservice-postgresql
